### ISSUE TITLE
many mismaches in  constraintlayout-compose 1.0.0-alpha05

### ISSUE THREAD

**Issue by masterofdaemon** [CaelumF/FigmaToCompose#12]
![изображение](https://user-images.githubusercontent.com/1370393/114924847-135a3180-9e37-11eb-9397-467a944000ae.png)

deps:
  compose_version = '1.0.0-beta04'
  implementation "androidx.constraintlayout:constraintlayout:2.0.4"
  implementation "androidx.constraintlayout:constraintlayout-compose:1.0.0-alpha05"

**Comment by CaelumF** [comment]
Hey, sorry I didn't see this earlier. This project is overdue an update both for changes in Compose and changes in Figma. I should have time to fix it at some point in June after I've finished up on something else that's occupying my evenings.

PRs are welcome of course, the code is a little unkempt and I'd understand if nobody wanted to touch it though haha

**Comment by masterofdaemon** [comment]
Haha, ive seen it, its nice to see thats the project is not completely dead), its great plugin

**Comment by CaelumF** [comment]
Hey @masterofdaemon , I've made some changes. Would you like to try again after these changes?

**Comment by CaelumF** [comment]
Another thing for anyone having issues here, make sure you have the ConstraintLayout _Compose_ composable imported and not the normal android one. You need to add it as a separate dependency right now fyi.

I'll close this since I think it's fixed.
