### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by UltraSina** [CaelumF/FigmaToCompose#19]
please create help video

**Comment by helmysaeed** [comment]
we need a video on how to run the plugin 
I don't understand what  is the command "Windows wsl bash dos2unix gradlew ./gradlew run --args="-config=application.conf" "

**Comment by antaki93** [comment]
I installed `wsl` from Windows Store. Then I installed `Ubuntu` from Windows Store. But:

```
user@WIN-XXX:/mnt/d/Code/FigmaToCompose$ ./gradlew run --args="-config=application.conf"
: not found2:
: not found18:
: not found24:
./gradlew: 68: Syntax error: word unexpected (expecting "in")
```

How can I fix it?

**Comment by antaki93** [comment]
I just installed `wsl` from Windows Store app. Then I installed `Ubuntu 22.04.2 LTS` from Windows Store app. And restart my computer.

I ran PowerShell as administrator and:
```
wsl
cd my/location/FigmaToCompose
sudo apt-get update
sudo apt-get install dos2unix
sudo dos2unix gradlew
./gradlew run --args="-config=application.conf"
```
I got an error about JAVA_HOME. Then:
```
wget https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.deb
sudo apt-get install ./jdk-17_linux-x64_bin.deb
./gradlew run --args="-config=application.conf"
```

And restart the computer again.

It helped me.

**Comment by vens8** [comment]
Hey, I found the readme confusing as well. But actually it's pretty simple:

Regardless of whether you're on mac, linux or windows, after cloning the repository, open the project on android studio and go to the terminal. You don't need WSL or anything. Just directly paste the following command and hit enter:

`./gradlew run --args="-config=application.conf"
`

After some time, the server starts running as can be seen below:
![image](https://github.com/CaelumF/FigmaToCompose/assets/55199947/3522a99c-2540-4b32-b5d7-4bbe42862ec1)


Then you can just select a node on your figma project and run the plugin as shown in the video. Click "generate" to get the composable code.
